"""Contains constants for filenames/paths."""
DATA_DIR = "./datasets/"
TEMP_DATA_DIR = "./datasets_temp/"
FORMATS_FILE = "all_formats"
THREAT_FILE = "_threats.npy"
TEAMMATE_FILE = "_team.npy"
TEMP_COUNTERS_FILE = "_counters.tmp"
DEX_PREFIX = "gen"
DEX_SUFFIX = ".dex"
DATE_FILE = "date"
TEST_DATA_DIR = "./test_data/"
CUSTOM_TEST_DATA_DIR = TEST_DATA_DIR + "custom_test_data/"
