"""Contains constants for filenames/paths."""
DATA_DIR = "./datasets/"
TEMP_DATA_DIR = "./datasets_temp/"
TOP_FORMATS_FILE = "top_formats"
THREAT_FILE = "_threats.npy"
TEAMMATE_FILE = "_team.npy"
DEX_PREFIX = "gen"
DEX_SUFFIX = ".dex"
